;;;; -*- Mode: Lisp; Syntax: ANSI-Common-Lisp; Base: 10 -*-
;;;; See the LICENSE file for licensing information.

(in-package #:cl-user)

(defpackage #:cl-sha1
  (:nicknames #:sha1)
  (:use :cl)
  (:import-from :cl-sha1-asd :*sha1-version*)
  (:export #:digest)
  (:documentation
   "Common Lisp @em{sha1} implementation.

    @begin[About]{section}

    About cl-sha1

    @end{section}

    @begin[Documentation]{section}

    This documentation was generated by @a[http://www.lichteblau.com/atdoc/doc/]{atdoc},
    the documentation generation system written by David Lichteblau.

    @end{section}
"))

